/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "gxkkltcbmyqqjwntybuy"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4a2tsdGNibXlxcWp3bnR5YnV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNTQxOTUsImV4cCI6MjA3NDYzMDE5NX0.4G8D6faCmREKMmhYmaeg-New-Wlwxp7R3nk-aeWFfms"